import "inspectable.idl";
import "Windows.UI.Core.idl";
import "Windows.ApplicationModel.Core.idl";

namespace Internal.Windows.ApplicationModel.Core
{
	[version(1.0)]
	[uuid(6090202d-2843-4ba5-9b0d-fc88eecd9ce5)]
	interface ICoreApplicationPrivate2 : IInspectable
	{
		HRESULT InitializeForAttach();

		HRESULT WaitForActivate([out, retval] Windows.UI.Core.CoreWindow** coreWindow);

		HRESULT CreateNonImmersiveView([out, retval] Windows.ApplicationModel.Core.CoreApplicationView** coreView);
	};
}
