import "inspectable.idl";
import "Windows.UI.Core.idl";

namespace Windows
{
	namespace UI
	{
		namespace Core
		{
			[version(1.0)]
			[uuid(CD292360-2763-4085-8A9F-74B224A29175)]
			interface ICoreWindowFactory
			{
				HRESULT CreateCoreWindow(HSTRING windowTitle,[out][retval] Windows.UI.Core.CoreWindow** window);
				[propget] HRESULT WindowReuseAllowed([out][retval]boolean* value);
				[propput] HRESULT WindowReuseAllowed([in]boolean value);
			}
		}
	}
}
