import "inspectable.idl";


namespace Windows
{
	namespace UI
	{
		namespace Xaml
		{
			namespace Hosting
			{
				runtimeclass XamlRuntime;

				[version(1.0)]
				[uuid(C805B0C0-6210-4E4F-B76A-E894E8B1A4AD)]
				[exclusiveto(Windows.UI.Xaml.Hosting.XamlRuntime)]
				interface IXamlRuntimeStatics : IInspectable
				{
					[propget] HRESULT EnableImmersiveColors([out][retval] boolean* value);
					[propput] HRESULT EnableImmersiveColors([in] boolean value);
					[propget] HRESULT EnableWebView([out][retval] boolean* value);
					[propput] HRESULT EnableWebView([in] boolean value);
				}

				[version(1.0)]
				[static(Windows.UI.Xaml.Hosting.IXamlRuntimeStatics, 1)]
				runtimeclass XamlRuntime
				{
				}
			}
		}
	}
}
